// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm2PqaAzLK9IvUeYBobu6qgQswcnZe5-0',
    appId: '1:1026837917599:web:5434423ffe1debab3217aa',
    messagingSenderId: '1026837917599',
    projectId: 'taskmanager-ced81',
    authDomain: 'taskmanager-ced81.firebaseapp.com',
    storageBucket: 'taskmanager-ced81.appspot.com',
    measurementId: 'G-0LDJ987RQS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRNVoQhXLte1E8rNuZj5GVyRKSIho1vPc',
    appId: '1:1026837917599:android:9467173da226a38a3217aa',
    messagingSenderId: '1026837917599',
    projectId: 'taskmanager-ced81',
    storageBucket: 'taskmanager-ced81.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu8WgeUBNQZIQz9E5Oxfl7PS96xrz87vo',
    appId: '1:1026837917599:ios:cd60646f1d5f68663217aa',
    messagingSenderId: '1026837917599',
    projectId: 'taskmanager-ced81',
    storageBucket: 'taskmanager-ced81.appspot.com',
    iosBundleId: 'com.softhon.taskManager',
  );
}
