include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
    strict_raw_type: error
    argument_type_not_assignable: error
    inference_failure_on_collection_literal: error
    always_declare_return_types: error
    unrelated_type_equality_checks: error
    avoid_void_async: error
    lines_longer_than_80_chars: ignore
    must_be_immutable: error

linter:
  rules:
    public_member_api_docs: false
    one_member_abstracts: false
    use_setters_to_change_properties: false
    lines_longer_than_80_chars: true
    sort_pub_dependencies: false