name: task_manager
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  azlistview: ^2.0.0
  sign_in_with_apple: ^5.0.0
  cloud_firestore: ^4.13.2
  cupertino_icons: ^1.0.2
  custom_refresh_indicator: ^3.0.0
  flash: ^3.0.5+2
  fluttertoast: ^8.2.4
  firebase_core: ^2.20.0
  firebase_auth: ^4.14.1
  firebase_analytics: ^10.7.0
  flutter_screenutil: ^5.7.0
  flutter_svg: ^2.0.7
  go_router: ^10.0.0
  google_fonts: ^6.1.0
  google_sign_in: ^6.1.6
  hooks_riverpod: ^2.4.3
  internet_connection_checker: ^1.0.0+1
  loading_animation_widget: ^1.2.0+4
  percent_indicator: ^4.2.3
  rive: ^0.11.13
  shared_preferences: ^2.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0+1


flutter: 
  assets: 
    - assets/images/
  uses-material-design: true
