name: task_manager
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.20.0
  flutter_screenutil: ^5.7.0
  go_router: ^10.0.0
  google_fonts: ^6.1.0
  hooks_riverpod: ^2.4.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0+1


flutter: 
  assets: 
    - assets/images/
  uses-material-design: true
