// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX7GInTsv75aGITyjWfMJ6BMB8ZfTNa20',
    appId: '1:936103878318:web:1aa804841c649c4b70973f',
    messagingSenderId: '936103878318',
    projectId: 'taskmanager-eb204',
    authDomain: 'taskmanager-eb204.firebaseapp.com',
    storageBucket: 'taskmanager-eb204.appspot.com',
    measurementId: 'G-Q5YFJV9806',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVuhOSn7U2Z4olQL6iWxInMwKd2mAfgyw',
    appId: '1:936103878318:android:ec3e76ef80cb99b070973f',
    messagingSenderId: '936103878318',
    projectId: 'taskmanager-eb204',
    storageBucket: 'taskmanager-eb204.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9lSrUTPrs1I5lZSA074xrf0o8TeimvDo',
    appId: '1:936103878318:ios:64f711edf479692370973f',
    messagingSenderId: '936103878318',
    projectId: 'taskmanager-eb204',
    storageBucket: 'taskmanager-eb204.appspot.com',
    androidClientId: '936103878318-20padl9dna13hlvhcdomoi1ho30g52cs.apps.googleusercontent.com',
    iosClientId: '936103878318-9odgq8ufmptjhpt81f4q5j7lusk052g2.apps.googleusercontent.com',
    iosBundleId: 'com.softhon.taskManager.dev',
  );
}
